import 'package:build/build.dart';
import 'package:dart2wgsl/src/parser.dart';
import 'package:dart2wgsl/src/validator.dart';
import 'package:dart2wgsl/src/transpiler.dart';

class ShaderBuilder implements Builder {
  @override
  final Map<String, List<String>> buildExtensions;

  ShaderBuilder({Map<String, List<String>>? buildExtensions})
    : buildExtensions =
          buildExtensions ??
          const {
            '.shader.dart': ['.wgsl.dart'],
          };

  @override
  Future<void> build(BuildStep buildStep) async {
    final inputId = buildStep.inputId;

    // Check if the input is a valid library
    if (!await buildStep.resolver.isLibrary(inputId)) return;

    final library = await buildStep.resolver.libraryFor(inputId);

    // Crawl dependencies
    final units = await crawlLibraryAsts(library);

    // Validate
    final errors = ShaderValidator.validate(units);
    if (errors.isNotEmpty) {
      log.severe('❌ Shader validation failed for ${inputId.path}:');
      for (final error in errors) {
        log.severe('  - $error');
      }
      throw StateError('Shader validation failed for ${inputId.path}');
    }

    // Transpile
    final wgslSource = ShaderTranspiler.transpile(units);

    // Derive camelCase constant variable name
    final filename = inputId.pathSegments.last;
    final baseName = filename.replaceAll('.shader.dart', '');
    final words = baseName.split(RegExp(r'[^a-zA-Z0-9]'))
      ..removeWhere((s) => s.isEmpty);
    String varName = 'shaderSource';
    if (words.isNotEmpty) {
      varName =
          words.first.toLowerCase() +
          words.skip(1).map((s) => s[0].toUpperCase() + s.substring(1)).join() +
          'Shader';
    }

    final outputContent =
        '''
// Generated by dart2wgsl. Do not modify.

const String $varName = r"""
$wgslSource""";
''';

    final outputId = AssetId(
      inputId.package,
      inputId.path.substring(0, inputId.path.length - '.shader.dart'.length) +
          '.wgsl.dart',
    );
    await buildStep.writeAsString(outputId, outputContent);
  }
}

Builder shaderBuilderFactory(BuilderOptions options) {
  return ShaderBuilder();
}
