// Generated by dart2wgsl. Do not modify.

// Structs
struct VertexInput {
  @location(0) position: vec3<f32>,
  @location(1) uv: vec2<f32>,
};

struct VertexOutput {
  @builtin(position) position: vec4<f32>,
  @location(0) uv: vec2<f32>,
};

// Uniforms & Resources
@group(0) @binding(0) var<uniform> uTime: f32;
@group(0) @binding(1) var<uniform> uResolution: vec2<f32>;

// Functions
@vertex
fn vsMain(input: VertexInput) -> VertexOutput {
  var out: VertexOutput = VertexOutput(vec4<f32>(input.position.x, input.position.y, input.position.z, 1.0), input.uv);
  return out;
}

@fragment
fn fsMain(input: VertexOutput) -> @location(0) vec4<f32> {
  var color: vec4<f32> = vec4<f32>(input.uv.x, input.uv.y, sin(uTime), 1.0);
  return color;
}
